Clean up the steps a bit

diff --git a/kapt b/kapt
--- a/kapt
+++ b/kapt
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+red=`tput setab 1 2>/dev/null || true`
+yellow=`tput setab 3 2>/dev/null || true`
+green=`tput setab 2 2>/dev/null || true`
+blue=`tput setab 4 2>/dev/null || true`
+reset=`tput sgr0 2>/dev/null || true`
+bold=`tput bold 2>/dev/null || true`
+
 die ( ) {
     echo
     echo "${bold}${red} $* ${reset}"
@@ -11,14 +18,22 @@ ensure ( ) {
     command -v $1 >/dev/null 2>&1 || die "ERROR: '$1' could be found in your PATH. Please install $1. $2"
 }
 
+info ( ) {
+    echo "${bold}${blue} $* ${reset}"
+}
+
 # Requires kotlin version 1.1.3+
 ensure kotlin 'https://kotlinlang.org/'
 
 # Load up arguments
 source args
 
+# Set KOTLIN_HOME
+# export KOTLIN_HOME=$KOTLIN_HOME
+
 # Step 1: Generate Stubs
-kotlinc \
+info "RUNNING STEP 1..."
+$KOTLIN_HOME/bin/kotlinc \
 -no-reflect \
 -no-stdlib \
 -no-jdk \
@@ -40,44 +55,58 @@ plugin:org.jetbrains.kotlin.kapt3:javacArguments=$JAVAC_ARGUMENTS,\
 plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=true,\
 plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=false,\
 plugin:org.jetbrains.kotlin.kapt3:verbose=true \
--Xplugin=$ANNOTATION_PROCESSOR
+-Xplugin=$ANNOTATION_PROCESSOR \
+&& info "STEP 1 COMPLETE." || die "STEP 1 FAILED."
 
 # Step 2: Run kapt
-# kotlinc \
-# -no-reflect \
-# -no-stdlib \
-# -no-jdk \
-# -verbose \
-# -classpath $CLASSPATH \
-# -d $OUTPUT \
-# -Xbuild-file=$BUILD_FILE \
-# -module-name app_debug \
-# -Xadd-compiler-builtins \
-# -Xload-builtins-from-dependencies \
-# -P plugin:org.jetbrains.kotlin.kapt3:aptMode=apt,\
-# $AP_CLASSPATH,\
-# plugin:org.jetbrains.kotlin.kapt3:sources=$SOURCES,\
-# plugin:org.jetbrains.kotlin.kapt3:classes=$CLASSES,\
-# plugin:org.jetbrains.kotlin.kapt3:incrementalData=$INCREMENTAL_DATA,\
-# plugin:org.jetbrains.kotlin.kapt3:stubs=$STUBS,\
-# plugin:org.jetbrains.kotlin.kapt3:apoptions=$AP_OPTIONS,\
-# plugin:org.jetbrains.kotlin.kapt3:javacArguments=$JAVAC_ARGUMENTS,\
-# plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=true,\
-# plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=false,\
-# plugin:org.jetbrains.kotlin.kapt3:verbose=true \
-# -Xplugin=$ANNOTATION_PROCESSOR
+info "RUNNING STEP 2..."
+$KOTLIN_HOME/bin/kotlinc \
+-no-reflect \
+-no-stdlib \
+-no-jdk \
+-verbose \
+-classpath $CLASSPATH \
+-d $OUTPUT \
+-Xbuild-file=$BUILD_FILE \
+-module-name $MODULE_NAME  \
+-Xadd-compiler-builtins \
+-Xload-builtins-from-dependencies \
+-P plugin:org.jetbrains.kotlin.kapt3:aptMode=apt,\
+$AP_CLASSPATH,\
+plugin:org.jetbrains.kotlin.kapt3:sources=$SOURCES,\
+plugin:org.jetbrains.kotlin.kapt3:classes=$CLASSES,\
+plugin:org.jetbrains.kotlin.kapt3:incrementalData=$INCREMENTAL_DATA,\
+plugin:org.jetbrains.kotlin.kapt3:stubs=$STUBS,\
+plugin:org.jetbrains.kotlin.kapt3:apoptions=$AP_OPTIONS,\
+plugin:org.jetbrains.kotlin.kapt3:javacArguments=$JAVAC_ARGUMENTS,\
+plugin:org.jetbrains.kotlin.kapt3:useLightAnalysis=true,\
+plugin:org.jetbrains.kotlin.kapt3:correctErrorTypes=false,\
+plugin:org.jetbrains.kotlin.kapt3:verbose=true \
+-Xplugin=$ANNOTATION_PROCESSOR \
+&& info "STEP 2 COMPLETE." || die "STEP 2 FAILED."
 
 # Step 3: Invoke kotlinc normally
-# kotlinc \
-# -no-reflect \
-# -no-stdlib \
-# -no-jdk \
-# -verbose \
-# -classpath $CLASSPATH \
-# -d $OUTPUT \
+info "RUNNING STEP 3..."
+$KOTLIN_HOME/bin/kotlinc \
+-no-reflect \
+-verbose \
+-classpath $CLASSPATH \
+-d $OUTPUT \
+-Xbuild-file=$BUILD_FILE \
+-module-name $MODULE_NAME \
+-Xadd-compiler-builtins \
+-Xload-builtins-from-dependencies \
+-Xplugin=$ANNOTATION_PROCESSOR \
+&& info "STEP 3 COMPLETE." || die "STEP 3 FAILED."
 
 # Step 4: Invoke javac
 # javac \
 # -source 7 \
 # -target 7 \
 # -sourcepath  \
+# -g \ 
+# -bootclasspath $BOOT_CLASSPATH \
+# -verbose \
+# -d $OUTPUT \
+# -s $SOURCE \
+# -classpath $CLASSPATH
